[workspace]
members = ["simulator"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.80"
build-utils = { path = "build-utils" }
cxx = "1.0.116"
cxx-build = { version = "1.0.116", features = ["parallel"] }
cgal = { path = "cgal" }
rayon = "1.8.1"
nalgebra = { version = "0.32.3" }
serde = { version = "1.0.197", features = ["derive", "rc"] }
test-case = "3.3.1"
paste = "1.0.14"
typed-builder = "0.18.1"
derive-getters = "0.3.0"
strum = { version = "0.26.1", features = ["derive"] }
strum_macros = "0.26.1"
enum-map = "2.7.3"
sealed = "0.5.0"
fxhash = "0.2.1"
nalgebra-ext = { path = "nalgebra-ext" }
function = { path = "function" }
approx = "0.5.1"
puffin = "0.19.0"
mesh = { path = "mesh" }

[profile.prod]
inherits = "release"
lto = "fat"
codegen-units = 1
strip = true
