[package]
name = "cgal"
version = "0.31.1"
edition.workspace = true

[dependencies]
cxx.workspace = true
cgal-sys = { path = "../cgal-sys" }
nalgebra.workspace = true
serde = { workspace = true, optional = true }
paste.workspace = true
derive-getters.workspace = true
rayon.workspace = true
regex = "1.10.4"

[dev-dependencies]
approx.workspace = true
test-case.workspace = true

[features]
serde = ["dep:serde"]
