[package]
name = "cgal-sys"
version = "0.18.0"
edition.workspace = true

[dependencies]
cxx.workspace = true
gmp-mpfr-sys = { version = "1.6.0", default-features = false, features = [
    "mpfr",
    "c-no-tests"
] }

[build-dependencies]
anyhow.workspace = true
boost-sys = { path = "../boost-sys" }
cxx-build.workspace = true
