[package]
name = "nalgebra-ext"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
nalgebra.workspace = true
enum-map.workspace = true
strum.workspace = true
strum_macros.workspace = true

[features]
serde = ["dep:serde", "nalgebra/serde-serialize"]
